services:
  odoo:
    container_name: odoo
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8070:8069"
    environment:
      HOST: postgres
      USER: ${POSTGRES_USER:-app}
      PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
    env_file:
      - .env
    networks:
      - odoo
    volumes:
      - ./odoo.conf:/etc/odoo/odoo.conf
      - ./addons:/mnt/extra-addons
      - odoo-data_vol:/var/lib/odoo
    command: --dev=all

  pgadmin_odoo:
    image: dpage/pgadmin4
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8008:80"
    networks:
      - odoo
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - pgadmin_data_odoo:/var/lib/pgadmin

  postgres:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-app} -d ${POSTGRES_DB:-app}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - postgres_vol_odoo:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - odoo
  mailpit:
    image: axllent/mailpit:v1.27
    networks:
      - odoo
    depends_on:
      - odoo
    container_name: training-mailpit
    restart: always
    ports:
      - "8025:8025"
      - "1025:1025"

  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=n8n
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - DB_TYPE=sqlite
      - NODE_ENV=development
      - GENERIC_TIMEZONE=Europe/Paris
    volumes:
      - ./n8n_data:/home/node/.n8n
    networks:
      - odoo
    # demo@email.com
    # DemoPassword123
    # http://n8n:5678/webhook-test/36c130d2-a71f-4475-8141-fe43921cbc6b
    # b0e0b1eaacebc3a3458b5cf82a8fc5957310e259
    # cdd8ce44fff9bf11c6e77a1ea6bd9938bce9d315
    # cec948766e70490a1eb64fc08cde8946c321dd47

networks:
  odoo:

volumes:
  postgres_vol_odoo:
  pgadmin_data_odoo:
  odoo-data_vol: